'use strict'

module.exports={
    routes:[
    {
        method:'GET',
        path:'/cars/updatename',
        handler:'custom.updateName',
        config:{
            auth:false,
            policies:[],
            middleware:[]
        }
    },
    {
        method:'GET',
        path:'/cars/seo',
        handler:'custom.updateSEO',
        config:{
            auth:false,
            policies:[],
            middleware:[]
        }
    },
    {
        method:'GET',
        path:'/cars/:slug',
        handler:'custom.getBySlug',
        config:{
            auth:false,
            policies:[],
            middleware:[]
        }
    }]
}